openapi: 3.0.0
info:
  title: FIPE Integration API
  version: 1.0.0
paths:
  /api/fipe/load-initial:
    post:
      summary: Trigger initial load of vehicle data
      responses:
        '202':
          description: Accepted for processing
components:
  schemas:
    Marca:
      type: object
      properties:
        codigo:
          type: string
        nome:
          type: string